export const lightStyles = {
  container: { background: '#ffffff' },
  text: '#000000',
  textSecondary: '#4a4a4a',
  accent: '#fbbf24',
  success: '#22c55e',
  warning: '#f59e0b',
  error: '#ef4444',
  sidebar: { background: '#f8f9fa', borderColor: '#e1e1e1' },
  sidebarHeader: {
    background: '#f8f9fa',
    borderColor: '#e1e1e1',
    borderBottom: '1px solid #e1e1e1',
    padding: 'var(--spacing-sm, 8px) var(--spacing-md, 12px)',
  },
  card: { background: '#ffffff', border: '1px solid #e1e1e1', boxShadow: 'none' },
  button: { background: '#ffffff', color: '#000000', border: '1px solid #e1e1e1' },
  iconButton: { background: '#ffffff', color: '#000000', border: '1px solid #e1e1e1' },
  header: {
    background: '#ffffff',
    borderColor: '#e1e1e1',
    borderBottom: '1px solid #e1e1e1',
    padding: 'var(--spacing-sm, 8px) var(--spacing-md, 12px)',
    minHeight: '40px',
  },
  input: { background: '#ffffff', color: '#000000', border: '1px solid #e1e1e1' },
  primaryButton: { background: '#fbbf24', color: '#000000' },
  accentButton: { background: '#fbbf24', color: '#000000' },
  dangerButton: { background: '#ef4444', color: '#ffffff' },
  activeNav: { background: '#fbbf24' },
  errorBackground: { background: 'rgba(239, 68, 68, 0.1)' },
  errorText: { color: '#ef4444' },
  taskBar: {
    background: '#f8f9fa',
    borderColor: '#e1e1e1',
  },
};

export const darkStyles = {
  container: { background: '#1a1a1a' },
  text: '#f5f5f5',
  textSecondary: '#d4d4d4',
  accent: '#fbbf24',
  success: '#22c55e',
  warning: '#f59e0b',
  error: '#ef4444',
  sidebar: { background: '#262626', borderColor: '#404040' },
  sidebarHeader: {
    background: '#262626',
    borderColor: '#404040',
    borderBottom: '1px solid #404040',
    padding: 'var(--spacing-sm, 8px) var(--spacing-md, 12px)',
  },
  card: { background: '#262626', border: '1px solid #404040', boxShadow: 'none' },
  button: { background: '#333333', color: '#f5f5f5', border: '1px solid #404040' },
  iconButton: { background: '#333333', color: '#f5f5f5', border: '1px solid #404040' },
  header: {
    background: '#1a1a1a',
    borderColor: '#404040',
    borderBottom: '1px solid #404040',
    padding: 'var(--spacing-sm, 8px) var(--spacing-md, 12px)',
    minHeight: '40px',
  },
  input: { background: '#333333', color: '#f5f5f5', border: '1px solid #404040' },
  primaryButton: { background: '#fbbf24', color: '#000000' },
  accentButton: { background: '#fbbf24', color: '#000000' },
  dangerButton: { background: '#ef4444', color: '#ffffff' },
  activeNav: { background: '#fbbf24' },
  errorBackground: { background: 'rgba(239, 68, 68, 0.1)' },
  errorText: { color: '#ef4444' },
  taskBar: {
    background: '#1a1a1a',
    borderColor: '#404040',
  },
};

export const sharedStyles = {
  container: {
    maxWidth: '1400px',
    margin: '0 auto',
    padding: '0 var(--spacing-lg, 16px)',
  },
  card: {
    padding: 'var(--spacing-lg, 16px)',
    borderRadius: 'var(--border-radius-lg, 8px)',
  },
  jobsList: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 'var(--spacing-sm, 8px)',
    marginTop: 'var(--spacing-md, 12px)',
  },
  jobItem: {
    padding: 'var(--spacing-sm, 8px) var(--spacing-md, 12px)',
    borderRadius: 0,
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    cursor: 'pointer',
    border: 'none',
    borderBottom: '1px solid',
    boxShadow: 'none',
  },
  printersList: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 'var(--spacing-sm, 8px)',
    marginTop: 'var(--spacing-md, 12px)',
  },
  printerCard: {
    padding: 'var(--spacing-sm, 8px) var(--spacing-md, 12px)',
    borderRadius: 0,
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    transition: 'background 0.15s ease',
    border: 'none',
    borderBottom: '1px solid',
    boxShadow: 'none',
  },
  form: {
    marginTop: 'var(--spacing-lg, 16px)',
  },
  input: {
    borderRadius: 'var(--border-radius-md, 6px)',
    fontSize: 'var(--font-size, 14px)',
  },
  fileButton: {
    padding: 'var(--spacing-sm, 8px) var(--spacing-lg, 16px)',
    border: 'none',
    borderRadius: 'var(--border-radius-md, 6px)',
    cursor: 'pointer',
    fontSize: 'var(--font-size, 14px)',
    fontWeight: '500',
  },
  actionButton: {
    padding: 'var(--spacing-sm, 8px) var(--spacing-lg, 16px)',
    border: 'none',
    borderRadius: 'var(--border-radius-md, 6px)',
    cursor: 'pointer',
    fontSize: 'var(--font-size, 14px)',
    transition: 'all 0.2s ease',
    fontWeight: '600',
  },
};

